// <auto-generated />
using FinTrack.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace FinTrack.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0")
                        .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("FinTrack.Shared.Models.Category", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").UseIdentityColumn();
                b.Property<string>("Color").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Icon").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("Type").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Categories");
            });

            modelBuilder.Entity("FinTrack.Shared.Models.Transaction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").UseIdentityColumn();
                b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
                b.Property<int>("CategoryId").HasColumnType("int");
                b.Property<DateTime>("Date").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("Type").HasColumnType("int");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("Id");
                b.HasIndex("CategoryId");
                b.HasIndex("UserId");
                b.ToTable("Transactions");
            });

            modelBuilder.Entity("FinTrack.Shared.Models.SavingsGoal", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").UseIdentityColumn();
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<decimal>("CurrentAmount").HasColumnType("decimal(18,2)");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<bool>("IsCompleted").HasColumnType("bit");
                b.Property<decimal>("TargetAmount").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("TargetDate").HasColumnType("datetime2");
                b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("SavingsGoals");
            });
#pragma warning restore 612, 618
        }
    }
}
