name: Build and deploy ASP.Net Core app to Azure Web App - fintrack-rg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore "FinTrack/FinTrack.sln" --verbosity minimal

      - name: Build solution
        run: dotnet build "FinTrack/FinTrack.sln" --configuration Release --no-restore --verbosity minimal

      - name: Publish API project
        run: dotnet publish "FinTrack/FinTrack.Server/FinTrack.Server.csproj" -c Release -o ./publish --no-build --verbosity minimal

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v5
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: .net-app

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v4
        with:
          app-name: 'fintrack-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
